CREATE TABLE USER(
    UserID INT NOT NULL primary key  AUTO_INCREMENT,
	UserName nvarchar(25) NOT NULL,
	Password nvarchar(25) NOT NULL,
	Status Bit 
)ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0 ;
/*
Test User Create
*/
INSERT INTO USER (UserName,Password,Status) VALUES ('okan','1234',1);
INSERT INTO USER (UserName,Password,Status) VALUES ('kaya','1234',1);

CREATE TABLE FIELD(
	FieldID INT NOT NULL primary key  AUTO_INCREMENT ,
	FieldName nvarchar(25) NOT NULL,
	FieldUrl nvarchar(50) NOT NULL,
    FieldInfo nvarchar(50),
    CenterLongitude Long NOT NULL,
    CenterLatitude Long NOT NULL,
    Area Long NOT NULL
)ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0 ;
/*
Test Field Create
*/
INSERT INTO FIELD (FieldName,FieldUrl,FieldInfo,CenterLongitude,CenterLatitude,Area) VALUES ('xxx','xxx','xxx',1.1,1.1,1);

CREATE TABLE USERFIELD(
	FieldID INT NOT NULL,
	UserID INT NOT NULL,
	CreatedDate  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (FieldID,UserID),
	CONSTRAINT FIELDS
	FOREIGN  KEY (FieldID) REFERENCES FIELD (FieldID)
	ON DELETE CASCADE ,
	CONSTRAINT USER
	FOREIGN  KEY (UserID) REFERENCES USER (UserID)
	ON DELETE CASCADE 
)ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0 ;
/*
Test User Create
*/
INSERT INTO USERFIELD (FieldID,UserID) VALUES (1,1);
Select * FROM USERFIELD; 

CREATE TABLE PRODUCT(
	ProductID INT NOT NULL primary key  AUTO_INCREMENT ,
	ProductName nvarchar(25) NOT NULL,
	PrductInfo nvarchar(50) NOT NULL
)ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0 ;
/*
Test PRODUCT Create
*/
INSERT INTO PRODUCT (ProductName,PrductInfo) VALUES ('product','xxx');
Select * FROM PRODUCT; 

CREATE TABLE FIELDPRODUCT(
	FieldID INT NOT NULL,
	ProductID INT NOT NULL,
	CreatedDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FinishDate timestamp,
	PRIMARY KEY (FieldID,ProductID),
	CONSTRAINT FIELDS
	FOREIGN  KEY (FieldID) REFERENCES FIELD (FieldID)
	ON DELETE CASCADE ,
	CONSTRAINT PRODUCT
	FOREIGN  KEY (ProductID) REFERENCES PRODUCT (ProductID)
	ON DELETE CASCADE 
)ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0 ;
/*
Test FIELDPRODUCT Create
*/
INSERT INTO FIELDPRODUCT (FieldID,ProductID) VALUES (1,1);
Select * FROM FIELDPRODUCT; 

CREATE TABLE STARTIRREGATIONINFO(
	StartIrregationInfoID INT NOT NULL primary key AUTO_INCREMENT,
	DateInformation timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    humidity int NOT NULL,
	temperature int NOT NULL
)ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0 ;
/*
Test STARTIRREGATIONINFO Create
*/
INSERT INTO STARTIRREGATIONINFO (humidity,temperature) VALUES (1,1);
Select * FROM STARTIRREGATIONINFO; 

CREATE TABLE FINISHIRREGATIONINFO(
	FinishIrregationInfoID INT NOT NULL primary key AUTO_INCREMENT,
	DateInformation timestamp,
    humidity int NOT NULL,
	temperature int NOT NULL
)ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0 ;
/*
Test FINISHIRREGATIONINFO Create
*/
INSERT INTO FINISHIRREGATIONINFO (humidity,temperature) VALUES (1,1);
Select * FROM FINISHIRREGATIONINFO; 

CREATE TABLE OTHERIRREGATIONINFO(
	OtherIrregationInfoID INT NOT NULL primary key AUTO_INCREMENT,
	DateInformation timestamp,
    GrowthValue int NOT NULL,
    AvarageHumidity int NOT NULL,
	AvarageTemperature int NOT NULL,
    LimitValueOutHumidity int NOT NULL,
    LimitValueOutTemperature int NOT NULL
)ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0 ;
/*
Test OTHERIRREGATIONINFO Create
*/
INSERT INTO OTHERIRREGATIONINFO (GrowthValue,AvarageHumidity,AvarageTemperature,LimitValueOutHumidity,LimitValueOutTemperature) VALUES (1,1,1,1,1);
Select * FROM OTHERIRREGATIONINFO; 

CREATE TABLE IRREGATION(
	IrregationID INT NOT NULL primary key AUTO_INCREMENT,
    ProductID INT NOT NULL,
    StartIrregationInfoID  INT NOT NULL,
    FinishIrregationInfoID  INT,
    OtherIrregationInfoID INT,
    IrregationAmount INT NOT NULL,
    CONSTRAINT PRODUCT
	FOREIGN  KEY (ProductID) REFERENCES PRODUCT (ProductID)
	ON DELETE CASCADE,
	CONSTRAINT STARTIRREGATIONINFO
	FOREIGN  KEY (StartIrregationInfoID) REFERENCES STARTIRREGATIONINFO (StartIrregationInfoID)
	ON DELETE CASCADE,
	CONSTRAINT FINISHIRREGATIONINFO
	FOREIGN  KEY (FinishIrregationInfoID) REFERENCES FINISHIRREGATIONINFO (FinishIrregationInfoID)
	ON DELETE CASCADE,
	CONSTRAINT OTHERIRREGATIONINFO
	FOREIGN  KEY (OtherIrregationInfoID) REFERENCES OTHERIRREGATIONINFO (OtherIrregationInfoID)
	ON DELETE CASCADE 
)ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;
/*
Test IRREGATION Create
*/
INSERT INTO IRREGATION (ProductID,StartIrregationInfoID,IrregationAmount) VALUES (1,1,1);
Select * FROM IRREGATION; 

CREATE TABLE OTHERFERTILIZATIONINFO(
	OtherFertılızatıonInfoID INT NOT NULL primary key AUTO_INCREMENT,
	DateInformation timestamp,
    GrowthValue int NOT NULL
)ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;
/*
Test OTHERFERTILIZATIONINFO Create
*/
INSERT INTO OTHERFERTILIZATIONINFO (GrowthValue) VALUES (1);
Select * FROM OTHERFERTILIZATIONINFO; 

CREATE TABLE FERTILIZATION(
	FertilizationID INT NOT NULL primary key AUTO_INCREMENT,
    ProductID INT NOT NULL,
	FertilizationAmount INT NOT NULL,
	OtherFertılızatıonInfoID INT,
	CreatedDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PRODUCT
	FOREIGN  KEY (ProductID) REFERENCES PRODUCT (ProductID)
	ON DELETE CASCADE,
	CONSTRAINT OTHERFERTILIZATIONINFO
	FOREIGN  KEY (OtherFertılızatıonInfoID) REFERENCES OTHERFERTILIZATIONINFO (OtherFertılızatıonInfoID)
	ON DELETE CASCADE
)ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0 ;
/*
Test FERTILIZATION Create
*/
INSERT INTO FERTILIZATION (ProductID,FertilizationAmount,OtherFertılızatıonInfoID) VALUES (1,1,1);
Select * FROM FERTILIZATION; 

/*
Check User Account
*/
SELECT UserID FROM USER WHERE UserName='okan' AND Password='1234';
/*
Get Field information
*/
SELECT * FROM FIELD AS F WHERE F.FieldID=1; 
/*
Get User Fields List
*/
SELECT F.FieldName,F.FieldID FROM FIELD AS F WHERE F.FieldID IN 
					 (SELECT UF.FieldID FROM USERFIELD AS UF  WHERE UF.UserID IN
					 ( SELECT U.UserID FROM USER AS U WHERE U.UserName ='okan'
                     AND U.Password='1234'
                     AND U.Status=1) );